### ISSUE TITLE
Is this really a database of compromises / vulnerabiliities?

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/oss-compromises#5]
Is this really a database of compromises? Or a database of externally-maintained fixes for publicly known vulnerabilities (intentional or not) that have not been repaired upstream? If it's really the latter, the name and description should match.

**Comment by jspeed-meyers** [comment]
My intention (and I think that of those cc'ed, but they can chime in) is for it to be the first: a database of compromises.

cc @piergiorgioladisa, @lumjjb, @inferno-chromium, @bureado

**Comment by inferno-chromium** [comment]
Yes, database of compromises over time and classifying them into attack classes.

**Comment by jspeed-meyers** [comment]
Closing unless David (or anyone else!) has a related question. If so, feel free to re-open.

**Comment by david-a-wheeler** [comment]
No need to re-open, you clearly answered the question. Thank you so much!
